version: '3'
services:
  php:
    image: php:7.4-cli
    working_dir: /var/www
    stdin_open: true
    tty: true
    command: bash -c "apt-get update; apt-get install -y libzip-dev zlib1g-dev; docker-php-ext-install zip; php -a"
    volumes:
      - ./:/var/www

